### PR TITLE
Add coverage reporting

### PR DESCRIPTION
**Pull request by tiran**
Signed-off-by: Christian Heimes <cheimes@redhat.com>

### CODE REVIEW

**Comment by tiran** [comment]
Coverage reporting depends on https://codecov.io/. IIRC the service is configured automatically.

**Comment by encukou** [comment]
Looks good! But let's add it to python-ldap, once pyldap is merged there.

**Comment by encukou** [comment]
Hm, also, can this do coverage for the C code?

**Comment by tiran** [comment]
We'd need to build the shared library with extra instrumentation ``CFLAGS=-O0 -pg -fprofile-arcs -ftest-coverage`` and LDFLAGS=``-lgcov`` and then use lcov to gather line coverage. I can look into lcov later.

**Comment by tiran** [comment]
I'll re-create #137, #139, #140, and this PR to https://github.com/python-ldap/python-ldap once you have merged pyldap into the project.

**Comment by tiran** [comment]
Patch has landed in https://github.com/python-ldap/python-ldap

**Pull request closed without merging**
