### PR TITLE
Test: schema: test_urlfetch from file

### PR DESCRIPTION
**Pull request by MartinBasti**
Testing of attributetypes and objectclasses parsing from file

Fixes: #79 

I inspired by `test_tokenizer`, and I'm not sure if that was the best idea, I miss asserts there, so let me know if that test should be done in different way.

### CODE REVIEW

**Comment by MartinBasti** [comment]
Well obliviously it needs some better error reporting, asserts instead of print? (see #82)

**Comment by encukou** [comment]
This belongs to `python-ldap`, so it'll need to be converted to the style that will be used there.

When `test_tokenizer` et al. are updated there, I'll modify this patch to match and submit it.

**Comment by MartinBasti** [comment]
Thanks, let me know if any help with this is needed

**Comment by encukou** [comment]
I've added Samba's `sambaHomePath` attribute type to the test to also check for an issue #58 solves.

**Comment by encukou** [comment]
I've updated this to the current master, so the tests still pass. Sorry for what it looks like on GitHub.

**Comment by MartinBasti** [comment]
Ok, no problem

**Comment by tiran** [comment]
I have written tests in upstream PR https://github.com/python-ldap/python-ldap/pull/52

**Pull request closed without merging**
