### PR TITLE
Merge changes from python-ldap 2.4.36

### PR DESCRIPTION
**Pull request by encukou**
There was heavy test refactoring, so I made a merge for every couple of upstream revisions to make this manageable.
There are no changes in `Lib/`, except metadata and the addition of a new `slapdtest` top-level module.

### CODE REVIEW

**Comment by encukou** [comment]
Note to myself: Probably running into an Ubuntu AppArmor issue. See the python-ldap list: https://mail.python.org/pipermail/python-ldap/2017q2/003925.html

**Comment by akkornel** [comment]
Looking around, I found this file:

https://github.com/travis-ci/travis-cookbooks/blob/master/cookbooks/travis_build_environment/templates/default/etc/init.d/disable-apparmor.sh.erb

That makes me wonder if they disable AppArmor on the workers.

If you do another Travis run, with the LOGLEVEL environment variable set to "1", that will generate tons of logs, including logs from the LDAP server.

In my case, I discovered the problem when slapd failed to open a socket file.

**Comment by encukou** [comment]
Turns out the test failures were a result of a bad merge.
This should be ready fro review now.

**Review by rbarrois — APPROVED** [review]
Looks great, thanks for all the hard work :)

**Comment by encukou** [comment]
Thank you for the reviews, Raphaël!

I updated this to current master (with some changes in newly added tests), and pushed.

Note that this breaks all tests written for  2.4.35 and below. I'll go through open pull requests and update them to the new test API. The changes aren't big, but can be annoying.
If anyone has unfinished work that adds new tests, feel free to submit it as WIP pull request and I'll modify it for you.

**Pull request merged**
