### PR TITLE
[py3]: Avoid changing dictionary while looping through it

### PR DESCRIPTION
**Pull request by stlaz**
This piece of code will break execution should it not be fixed.

### CODE REVIEW

**Review by rbarrois — COMMENTED** [review]
Indeed, this is similar to the fix in https://github.com/pyldap/pyldap/commit/60801268c56784f86847caa400dc0aad1699eb26.

Do you think you could add a test for this, and ideally push the fix upstream?

**Comment by stlaz** [comment]
I'll try to find which piece of IPA tries to use this and will see if this could easily be tested.

**Comment by tiran** [comment]
Please drop the call to ``keys`` function and just use ``for a in list(r_may):``. ``list(adict)`` returns a list of keys on both Python 2 and 3. It avoids an unnecessary method call and copy.

**Review by tiran — CHANGES_REQUESTED** [review]
drop ``keys()``

**Comment by stlaz** [comment]
Thanks, Christian, I was fixing this rather blindly doing something else in the meantime, that's a good improvement.

**Comment by encukou** [comment]
There's another similar problem use a few lines down.
@stlaz, do you plan to work on this further, or should I take over here? I can add  d5bbfe81dbb51874709e16aad0d555943f0961f3

**Comment by stlaz** [comment]
@encukou I can enhance this PR that way but I probably won't have this finished today

**Comment by encukou** [comment]
@tiran: Actually, the `keys()` is necessary. This is not a regular dict, but a python-ldap `cidict` (though it only holds OIDs).
And `cidict` wasn't designed for just iterating over it.

**Comment by encukou** [comment]
I've opened https://github.com/pyldap/pyldap/pull/105 with an additional fix and some test.

**Comment by stlaz** [comment]
@encukou Thanks! Sorry I had some other stuff to do and was not sure how much time this would take me. I guess we can close this PR being superseeded by yours.

**Comment by encukou** [comment]
OK

**Pull request closed without merging**
