### PR TITLE
Sync with upstream 2.4.35

### PR DESCRIPTION
**Pull request by encukou**
This brings in changes from 2.4.30, 2.4.32, and <s>CVS head</s> 2.4.35, with accompanying fixes so the tests pass <s>(in case of CVS head, one test doesn't pass, but the same issue appears upstream)</s>.

Sending it as a PR so work can be based on top of this; hopefully that'll help avoid duplicate work.

### CODE REVIEW

**Comment by encukou** [comment]
This PR now brings in changes up to python-ldap 2.4.35 (including 2.4.33 for #87).

I also spent some hours looking at the release after that, 2.4.36, but I still didn't get through merging in the upstream refactoring. I suggest we release 2.4.35 soon, and work on the test refactoring afterwards.

**Comment by encukou** [comment]
Could I get a review?

**Comment by rbarrois** [comment]
@encukou I'll do my best to review it this week-end.

**Comment by encukou** [comment]
Any update?
I can do the release myself, if needed.

**Comment by rbarrois** [comment]
Looks good, minus some issues in the 3c46166 branch merge: we should not have to use ``isinstance(x, bytes)``, and use ``self._unbytesify_value`` as needed.

I'll fix this in a following commit.

**Comment by encukou** [comment]
Sweet, thanks!
I'll do a release tomorrow if nothing comes up.

**Comment by encukou** [comment]
Released 2.4.35: https://pypi.python.org/pypi/pyldap
This is my first pyldap release; hopefully I did everything right.

**Comment by rbarrois** [comment]
Great!

I've just tested the generated package, it looks fine (at least, all django-ldapdb tests pass properly).

**Pull request merged**
