### PR TITLE
v2.4.25

### PR DESCRIPTION
**Pull request by encukou**
Upstream has released 2.4.25 (shortly after 2.4.23 which had a serious bug and 2.4.24 which was skipped).
The changes are mainly in docs, plus there's a bugfix.

@rbarrois, if this looks good to you could merge and release to PyPI?

### CODE REVIEW

**Comment by encukou** [comment]
Tox worked for me on 2.7, and the exact same commit passed CI here: https://travis-ci.org/encukou/pyldap/builds/103860257
So I'd guess the timeout is a Travis issue.

**Comment by hroncok** [comment]
I've rerun the test on Travis and it has passed.

**Comment by encukou** [comment]
@rbarrois, will you find time to do the release?

**Comment by rbarrois** [comment]
@encukou Yep, I'm on it :)

By the way, if you have a PyPI username, I can give you the rights too :)

**Comment by encukou** [comment]
I'm `encukou` on PyPI as well.

**Comment by rbarrois** [comment]
@encukou I've added you as a maintainer, this should hopefully speed up future version bumps :)

**Pull request merged**
