### PR TITLE
Cherry-pick changes from python-ldap's development branch

### PR DESCRIPTION
**Pull request by encukou**
These are changes I want to merge into pyldap, and then merge pyldap into python-ldap.

When reviewing, please pay some extra attention to syncrepl. In `test_refreshAndPersist_poll_only`, are the types in `poll_result` right? This here is a bit out of my league.

(The two merge commits are intentional -- the first one is for python-ldap.)

### CODE REVIEW

**Comment by tiran** [comment]
Do you remember which commits you have skipped? I suspect you did not merge the commits that touch ``PyString_*`` to ``PyBytes_*``. Any more commits that are worth mentioning?

**Comment by encukou** [comment]
Ah, sorry for not pointing that out.

A list is in the commit message in the first merge commit, "Merge Michael's work from the CVS repository on SourceForge".

**Comment by tiran** [comment]
``test_refreshAndPersist_poll_only`` looks ok to me. It's exactly like in upstream. The function passed ``all=0`` to get out of the loop eagerly.

**Review by tiran — APPROVED** [review]
LGTM

**Pull request merged**
