### PR TITLE
Retire pyldap

### PR DESCRIPTION
**Pull request by encukou**
All files are removed, except for README, LICENSE, setup.py and requirements.txt
All these remaining files are now stubs redirecting to python-ldap.

This should be released to PyPI when python-ldap 3.0.0 comes out of beta.

### CODE REVIEW

**Comment by hroncok** [comment]
I suggest to add some links to the README. python-ldap.org, github repo, etc.

**Comment by tiran** [comment]
I also suggest to remote all files on master and replace master with a single README.

**Comment by encukou** [comment]
Added links. That's a good idea!

@tiran, I'd rather have the source for the shim package here.

**Comment by tiran** [comment]
@encukou Have you considered the archive option?

>  Archive repository
>
> This will make the pyldap/pyldap repository, issues, pull requests, labels, milestones, projects, wiki, releases, commits, tags, branches, reactions and comments read-only and disable any future comments. The repository can still be forked.
>
> Ensure you've changed any repository settings, considered closing all open issues and pull requests and updated your README before you archive this repository.
> 
> Once archived, you can unarchive the repository at any time.

**Comment by encukou** [comment]
Yes, thanks for the reminder!
I'd like to do that some time after python-ldap 3.0. For now, some discussion still happens here, and I don't think it's all that bad.

Added to https://github.com/python-ldap/python-ldap/issues/1

**Comment by bersace** [comment]
Congratulation to everyone for pyldap and this big move !

**Pull request merged**
